### ISSUE TITLE
Intended Usage

### ISSUE THREAD

**Issue by JosXa** [elapouya/NoAttr#2]
Hi there,
while checking out the examples and making a [short PR for the README](https://github.com/elapouya/NoAttr/pull/1), I was originally gonna add the following description, as that was what I expected the library to be doing:

```
When is this useful?
####################

External APIs often return complex objects without consistent type annotations and you might not be sure which fields and properties are optional, causing you to either write code that fails at runtime, or force you to litter your logic with defensive constructs such as chained condition clauses or exception handlers.

When you repeatedly spot code like the following in your project, you know you have a valid use case for *NoAttr*: ::

    if the_attr := obj.my_attr:
        if hasattr(the_attr, "some_key") and (result := the_key.some_key.more_nested_stuff):
            print(result)

This snippet of code has multiple points of failure and can be rewritten to look a lot more elegant using *NoAttr*:
...
⬆️ And here is where I noticed that's not actually what it does.
```

So the question is if you see a way to amend an existing third-party object's attribute hierarchy, or whether the project is really only useful for library authors (in order to replace all `None` values with `NoAttr` instances as I imagine it).

I imagine it could behave a bit like MagicMock (but less expensive) and allow something like
```
NoAttr(some_third_party_obj).a.b.c.d
```
by holding the underlying value.. 🤔

**Comment by elapouya** [comment]
Hi,
The documentation is quite self-explanatory I think. It can be used with you own application if you construct object with attributes created on-the-fly and thus you do not know their presence when accessing them.
Note : NoAttr is an object not a function/class

**Comment by JosXa** [comment]
Okay. That sounds like it is aimed predominantly towards library authors looking to provide a convenient API...
